spring:
  application.name: notesmanager
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        show_sql: true
    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: none
  liquibase:
    enabled: true
    label-filter: migration

  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_URL}
        enabled: true

  messages:
    fallback-to-system-locale: false
    basename: "i18n/exception/details"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: always
    configprops:
      show-values: always
