spring:
  application.name: notesmanager
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        show_sql: true
    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: create
  liquibase:
    enabled: false
